description: |
  Sensor driver for the Alps EC11 rotary encoder

compatible: "alps,ec11"

properties:
  label:
    type: string
    required: true
  a-gpios:
    type: phandle-array
    required: true
    description: A pin for the encoder
  b-gpios:
    type: phandle-array
    required: true
    description: A pin for the encoder
  resolution:
    type: int
    description: Number of pulses per tick
    deprecated: true
    required: false
  steps:
    type: int
    description: Number of pulses in one full rotation
    required: false
